name: sipesel
description: Sistem Pengelolaan Sewa Kios - Aplikasi Mobile Flutter UAS
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  # Firebase
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  # QR Code
  qr_flutter: ^4.1.0
  # Screenshot & Save
  screenshot: ^3.0.0
  path_provider: ^2.1.2
  # Chart
  fl_chart: ^0.68.0
  # Export
  excel: ^4.0.3
  pdf: ^3.10.8
  printing: ^5.12.0
  # WhatsApp & URL
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true